DROP TABLE ORDERDETAIL;
DROP TABLE ADDRESS;
DROP TABLE PAYMENTMETHOD;
DROP TABLE VENDORS;
DROP TABLE INVENTORY;
DROP TABLE STORE;
DROP TABLE BRANDBELONGTO;
DROP TABLE BRAND;
DROP TABLE PRODUCTBELONGTO;
DROP TABLE CARTDETAIL;
DROP TABLE CART;
DROP TABLE PRODUCT;
DROP TABLE PRODUCT_TYPE;
DROP TABLE ACCOUNT;
DROP TABLE ORDERS;
DROP TABLE CUSTOMERS;

